In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("Downloads/Indian_House_Rent_Dataset.csv")

In [3]:
df.head()

Posted On       BHK    Size       Floor    Area Type  \
0         NaN       2.0  1100.0         NaN   Super Area   
1  2022-05-13       2.0   800.0  1 out of 3   Super Area   
2  2022-05-16       2.0  1000.0  1 out of 3   Super Area   
3  2022-07-04       2.0   800.0  1 out of 2   Super Area   
4  2022-05-09  2.0 room   850.0  1 out of 2  Carpet Area   

              Area Locality             City Furnishing Status  \
0                    Bandel  India-! Kolkata       Unfurnished   
1  Phool Bagan, Kankurgachi  India-! Kolkata    Semi-Furnished   
2   Salt Lake City Sector 2  India-- Kolkata    Semi-Furnished   
3                       NaN              NaN       Unfurnished   
4             South Dum Dum  India-^ Kolkata       Unfurnished   

     Tenant Preferred Bathroom Point of Contact   Rent  
0  Bach^elors/Fam.ily      2.0    Contact Owner  10000  
1  Bachelors\/Family*      NaN              NaN  20000  
2                 NaN      1.0    Contact Owner  17000  
3  Bachel]ors/F@amily      1.0              NaN  10000  
4         Bache[lors&      1.0    Contact Owner   7500

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Posted On          4084 non-null   object
 1   BHK                3963 non-null   object
 2   Size               3826 non-null   object
 3   Floor              3960 non-null   object
 4   Area Type          3804 non-null   object
 5   Area Locality      4146 non-null   object
 6   City               4091 non-null   object
 7   Furnishing Status  4042 non-null   object
 8   Tenant Preferred   4094 non-null   object
 9   Bathroom           4205 non-null   object
 10  Point of Contact   4137 non-null   object
 11  Rent               4746 non-null   int64 
dtypes: int64(1), object(11)
memory usage: 445.1+ KB


In [5]:
df.describe()

Rent
count  4.746000e+03
mean   3.499345e+04
std    7.810641e+04
min    1.200000e+03
25%    1.000000e+04
50%    1.600000e+04
75%    3.300000e+04
max    3.500000e+06

In [6]:
df.isnull().sum()

Posted On            662
BHK                  783
Size                 920
Floor                786
Area Type            942
Area Locality        600
City                 655
Furnishing Status    704
Tenant Preferred     652
Bathroom             541
Point of Contact     609
Rent                   0
dtype: int64

In [7]:
df['BHK'].unique()

array(['2.0', '2.0 room', '1.0', nan, '3.0', '1.0 room', '6.0', '4.0',
       '3.0 room', '5.0', '5.0 room', '4.0 room', '6.0 room'],
      dtype=object)

In [8]:
df['BHK'] = df['BHK'].str.extract(r'(\d+)')

In [9]:
df['BHK'].unique()

array(['2', '1', nan, '3', '6', '4', '5'], dtype=object)

In [10]:
df['BHK'].value_counts()

BHK
2    1921
1     947
3     911
4     162
5      17
6       5
Name: count, dtype: int64

In [11]:
df['BHK'] = pd.to_numeric(df['BHK'])

In [12]:
df['Size'].unique()

array(['1100.0', '800.0', '1000.0', '850.0', '600.0', '700.0', '250.0',
       nan, '1200.0', '400.0', '375.0', '900.0', '1286.0', '2000.0',
       '650.0', '300.0', '1600.0', '355.0', '350.0', '550.0', '500.0',
       '630.0', '270.0', '1500.0', '1068.0', '150.0', '450.0', '720.0',
       '680.0', '950.0', '1800.0', '480.0', '435.0', '1300.0', '1450.0',
       '750.0', '220.0', '20.0', '200.0', '840.0', '740.0', '490.0',
       '280.0', '120.0', '1220.0', '670.0', '240.0', '2200.0', '685.0',
       '44.0', '392.0', '710.0', '1400.0', '160.0', '1250.0', '839.0',
       '230.0', '620.0', '1350.0Square Feet', '723.0', '320.0', '2160.0',
       '1700.0', '130.0', '505.0', '4000.0', '1190.0', '1012.0', '812.0',
       '420.0', '1750.0', '830.0', '1050.0', '960.0', '756.0', '288.0',
       '1600.0Square Feet', '986.0', '322.0', '957.0', '1430.0', '1320.0',
       '650.0Square Feet', '475.0', '550.0Square Feet', '570.0', '460.0',
       '530.0', '850.0Square Feet', '558.0', '175.0', '721.0',

In [13]:
df['Size'] = df['Size'].str.extract(r'(\d+)')

In [14]:
df['Size'].unique()

array(['1100', '800', '1000', '850', '600', '700', '250', nan, '1200',
       '400', '375', '900', '1286', '2000', '650', '300', '1600', '355',
       '350', '550', '500', '630', '270', '1500', '1068', '150', '450',
       '720', '680', '950', '1800', '480', '435', '1300', '1450', '750',
       '220', '20', '200', '840', '740', '490', '280', '120', '1220',
       '670', '240', '2200', '685', '44', '392', '710', '1400', '160',
       '1250', '839', '230', '620', '1350', '723', '320', '2160', '1700',
       '130', '505', '4000', '1190', '1012', '812', '420', '1750', '830',
       '1050', '960', '756', '288', '986', '322', '957', '1430', '1320',
       '475', '570', '460', '530', '558', '175', '721', '2210', '675',
       '1880', '640', '518', '777', '2308', '890', '888', '275', '424',
       '610', '722', '1150', '470', '410', '932', '560', '3000', '751',
       '696', '2500', '715', '1337', '737', '760', '365', '1330', '2600',
       '1783', '565', '1080', '825', '1545', '780', '695', '

In [15]:
df['Size'] = pd.to_numeric(df['Size'])

In [16]:
df['Size'].describe()

count    3826.000000
mean      967.802405
std       627.895502
min        10.000000
25%       551.250000
50%       845.500000
75%      1200.000000
max      7000.000000
Name: Size, dtype: float64

In [17]:
df['Floor'].unique()

array([nan, '1 out of 3', '1 out of 2', 'Ground out of 1',
       'Ground out of 4', '1 out of 4', '1 out of 1', 'Ground out of 2',
       'Ground out of 3', '2 out of 3', '4 out of 5', '2 out of 2',
       '2 out of 5', '3 out of 3', '5 out of 5', '4 out of 4',
       '7 out of 8', '2 out of 4', '3 out of 4', '1 out of 5',
       'Ground out of 6', 'Upper Basement out of 4', 'Ground out of 5',
       '3 out of 5', '11 out of 19', '5 out of 10', '11 out of 14',
       'Lower Basement out of 2', '2 out of 7', '4 out of 10',
       '7 out of 10', '2 out of 13', '6 out of 7', '4 out of 7',
       '14 out of 14', '43 out of 78', '2 out of 8', '13 out of 18',
       '18 out of 24', '3 out of 7', '17 out of 31', '11 out of 21',
       '14 out of 23', '19 out of 24', '3 out of 21', '8 out of 8',
       '6 out of 12', '4 out of 58', '60 out of 66', '34 out of 48',
       '5 out of 8', '14 out of 40', '5 out of 7', '26 out of 44',
       '1 out of 8', '25 out of 42', '25 out of 41', '53 out of 

In [18]:
df['Floor_number'] = df['Floor'].str.split(" out of ").str[0]
df['Total_Floors'] = df['Floor'].str.split(" out of ").str[1]

In [19]:
df['Floor_number'].unique()

array([nan, '1', 'Ground', '2', '4', '3', '5', '7', 'Upper Basement',
       '11', 'Lower Basement', '6', '14', '43', '13', '18', '17', '19',
       '8', '60', '34', '26', '25', '53', '16', '39', '10', '12', '32',
       '47', '28', '9', '20', '15', '65', '40', '37', '21', '30', '35',
       '22', '44', '41', '46', '27', '48', '50', '24', '29', '23', '36',
       '76', '45'], dtype=object)

In [20]:
df['Floor_number'].replace({'Ground': 0 ,'Upper Basement':-1 , 'Lower Basement':-2}, inplace=True)

In [21]:
df['Floor_number'].unique()

array([nan, '1', 0, '2', '4', '3', '5', '7', -1, '11', -2, '6', '14',
       '43', '13', '18', '17', '19', '8', '60', '34', '26', '25', '53',
       '16', '39', '10', '12', '32', '47', '28', '9', '20', '15', '65',
       '40', '37', '21', '30', '35', '22', '44', '41', '46', '27', '48',
       '50', '24', '29', '23', '36', '76', '45'], dtype=object)

In [22]:
df['Total_Floors'].unique()

array([nan, '3', '2', '1', '4', '5', '8', '6', '19', '10', '14', '7',
       '13', '78', '18', '24', '31', '21', '23', '12', '58', '66', '48',
       '40', '44', '42', '41', '20', '60', '32', '89', '30', '15', '16',
       '11', '28', '22', '17', '45', '35', '9', '75', '38', '51', '43',
       '25', '27', '76', '36', '37', '55', '68', '29', '26', '50', '62',
       '52', '54', '33', '46', '85', '71', '81', '34'], dtype=object)

In [23]:
df['Floor_number'] = pd.to_numeric(df['Floor_number'])
df['Total_Floors'] = pd.to_numeric(df['Total_Floors'])

In [24]:
df['Area Type'].unique()

array(['Super Area', 'Carpet Area', nan, 'CARPET AREA', 'SUPER AREA',
       'Built Area'], dtype=object)

In [25]:
df['Area Type'] = df['Area Type'].str.capitalize()

In [26]:
df['Area Type'].unique()

array(['Super area', 'Carpet area', nan, 'Built area'], dtype=object)

In [27]:
df['Area Locality'].sample(20)

432                    Salt Lake City Sector 2
2486    Safdarjung Development Area, Hauz Khas
3413                                       NaN
3212                                Mandaiveli
2920                                 Pitampura
648                       Lake Florence, Powai
4067               Ashok Nagar, Himayath Nagar
2595                              Gautam Nagar
3208                                   T Nagar
1093            Island City Centre, Dadar East
3501                  Moulivakkam, Moulivakkam
1585                                       NaN
3621                                Arumbakkam
1520                                Nri Layout
1398                                       NaN
4411                            Petbasheerabad
1867                                       NaN
4053                                IAS Colony
901                              Borivali East
3953                               Narayanguda
Name: Area Locality, dtype: object

In [28]:
df['City'].unique()

array(['India-! Kolkata', 'India-- Kolkata', nan, 'India-^ Kolkata',
       'India-\\ Kolkata', 'India-% Kolkata', ',-9 Kolkata',
       'India-/ Kolkata', '(-9 Kolkata', '^-9 Kolkata', '--9 Kolkata',
       'India-* Kolkata', 'India-; Kolkata', 'India-. Kolkata',
       '!-9 Kolkata', ':-9 Kolkata', '\\-9 Kolkata', ';-9 Kolkata',
       'India-> Kolkata', '.-9 Kolkata', 'India-@ Kolkata',
       'India-{ Kolkata', 'India-[ Kolkata', 'India-| Kolkata',
       'India-} Kolkata', '"-9 Kolkata', '|-9 Kolkata', "'-9 Kolkata",
       '>-9 Kolkata', 'India-? Kolkata', '}-9 Kolkata', '#-9 Kolkata',
       'India-$ Kolkata', ']-9 Kolkata', 'India-< Kolkata', '$-9 Kolkata',
       'India-] Kolkata', '<-9 Kolkata', 'India-: Kolkata',
       'India-# Kolkata', 'India-+ Kolkata', '+-9 Kolkata',
       'India-& Kolkata', 'India-, Kolkata', '%-9 Kolkata',
       'India-( Kolkata', 'India-_ Kolkata', '@-9 Kolkata', '=-9 Kolkata',
       'India-" Kolkata', '/-9 Kolkata', '_-9 Kolkata', '?-9 Kolkata',


In [29]:
df['City'] = df['City'].str.split(' ').str[1]

In [30]:
df['City'].unique()

array(['Kolkata', nan, 'Mumbai', 'Bangalore', 'Delhi', 'Chennai',
       'Hyderabad'], dtype=object)

In [31]:
df['Furnishing Status'].unique()

array(['Unfurnished', 'Semi-Furnished', 'Furnished', nan], dtype=object)

In [32]:
df['Tenant Preferred'].unique()

array(['Bach^elors/Fam.ily', 'Bachelors\\/Family*', nan, ...,
       '!Bachelors+/Family', '$Family%', 'Bachelo%rs:'], dtype=object)

In [33]:
df['Tenant Preferred'] = df['Tenant Preferred'].str.replace(r'[^a-zA-Z]', '', regex=True)

In [34]:
df['Tenant Preferred'].unique()

array(['BachelorsFamily', nan, 'Bachelors', 'Family'], dtype=object)

In [35]:
df['Tenant Preferred'] = df['Tenant Preferred'].str.replace('BachelorsFamily', 'Bachelors/Family')

In [36]:
df['Tenant Preferred'].unique()

array(['Bachelors/Family', nan, 'Bachelors', 'Family'], dtype=object)

In [37]:
df['Bathroom'].unique()

array(['2.0', nan, '1.0', '1.0 Bathrooms', '2.0 Bathrooms', '3.0', '4.0',
       '5.0', '3.0 Bathrooms', '5.0 Bathrooms', '6.0', '4.0 Bathrooms',
       '7.0', '10.0'], dtype=object)

In [38]:
df['Bathroom'] = df['Bathroom'].str.extract(r'(\d+)')

In [39]:
df['Bathroom'] = pd.to_numeric(df['Bathroom'])

In [40]:
df['Point of Contact'].unique()

array(['Contact Owner', nan, 'Contact Agent'], dtype=object)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Posted On          4084 non-null   object 
 1   BHK                3963 non-null   float64
 2   Size               3826 non-null   float64
 3   Floor              3960 non-null   object 
 4   Area Type          3804 non-null   object 
 5   Area Locality      4146 non-null   object 
 6   City               4091 non-null   object 
 7   Furnishing Status  4042 non-null   object 
 8   Tenant Preferred   4094 non-null   object 
 9   Bathroom           4205 non-null   float64
 10  Point of Contact   4137 non-null   object 
 11  Rent               4746 non-null   int64  
 12  Floor_number       3960 non-null   float64
 13  Total_Floors       3957 non-null   float64
dtypes: float64(5), int64(1), object(8)
memory usage: 519.2+ KB
